"""Add movie_title, genre, status columns to watchlists table

Revision ID: 12ca7f04c330
Revises: 544f5875c6c0
Create Date: 2025-07-31 12:32:40.548764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12ca7f04c330'
down_revision = '544f5875c6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('movie_title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('genre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('watchlists', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('genre')
        batch_op.drop_column('movie_title')

    # ### end Alembic commands ###
