"""Add bio column to User model

Revision ID: 544f5875c6c0
Revises: 
Create Date: 2025-07-30 17:19:20.331343

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '544f5875c6c0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('bio')

    # ### end Alembic commands ###
